(function () {
  const e = React.createElement, PROTOCOL_VERSION = 3, STORAGE_KEY = "aemp_b_hover_signing_key_jwk", MAGIC = "AEMPWM3";
  const viewerCssSnippet = () => `.aemp-viewer { position: relative; display: inline-block; }
.aemp-viewer img { display: block; max-width: 100%; height: auto; }
.aemp-hover-mark {
  position: absolute; right: 18px; bottom: 18px; padding: 8px 10px;
  font: 700 12px/1 monospace; letter-spacing: .08em;
  color: rgba(255,255,255,.12); background: rgba(255,255,255,.04);
  image-rendering: pixelated; transition: all .18s ease;
}
.aemp-viewer:hover .aemp-hover-mark,.aemp-hover-mark:focus {
  color: rgba(255,255,255,.98); background: rgba(2,6,23,.86);
  box-shadow: 0 0 0 1px rgba(255,255,255,.35), 0 0 18px rgba(147,197,253,.28);
}`;
  const viewerHtmlSnippet = s => `<div class="aemp-viewer">\n  <img src="your-image.png" alt="AEM-P image" />\n  <div class="aemp-hover-mark" aria-label="AI-generated, verified state ${s}">AI·${s}</div>\n</div>`;
  const uuidLike = () => { const b = new Uint8Array(16); crypto.getRandomValues(b); return [...b].map((v, i) => (i === 4 || i === 6 || i === 8 || i === 10 ? "-" : "") + v.toString(16).padStart(2, "0")).join("") };
  const nowIso = () => new Date().toISOString(), clamp = (v, min, max) => Math.max(min, Math.min(max, v));
  const stripManifestForSigning = m => { const c = JSON.parse(JSON.stringify(m)); delete c.signature_b64; return c; };
  const sha256Hex = async t => Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256", new TextEncoder().encode(t)))).map(b => b.toString(16).padStart(2, "0")).join("");
  const arrayBufferToBase64 = buffer => { const bytes = new Uint8Array(buffer); let s = ""; for (let i = 0; i < bytes.length; i++)s += String.fromCharCode(bytes[i]); return btoa(s) };
  const base64ToUint8Array = b64 => { const bin = atob(b64), out = new Uint8Array(bin.length); for (let i = 0; i < bin.length; i++)out[i] = bin.charCodeAt(i); return out };
  const downloadBlob = (filename, blob) => { const url = URL.createObjectURL(blob), a = document.createElement("a"); a.href = url; a.download = filename; a.click(); setTimeout(() => URL.revokeObjectURL(url), 500) };
  const deriveVisibleState = (editCount, broken) => broken ? "X" : editCount <= 0 ? "0" : editCount >= 9 ? "9" : String(editCount);
  function createDemoBaseCanvas() { const c = document.createElement("canvas"); c.width = 1024; c.height = 768; const ctx = c.getContext("2d"), g = ctx.createLinearGradient(0, 0, c.width, c.height); g.addColorStop(0, "#312e81"); g.addColorStop(.5, "#0f766e"); g.addColorStop(1, "#1d4ed8"); ctx.fillStyle = g; ctx.fillRect(0, 0, c.width, c.height); for (let i = 0; i < 20; i++) { ctx.globalAlpha = .16; ctx.fillStyle = i % 2 ? "#fff" : "#7dd3fc"; ctx.beginPath(); ctx.arc(80 + i * 44, 120 + (i % 3) * 120, 28 + (i % 4) * 16, 0, Math.PI * 2); ctx.fill() } ctx.globalAlpha = 1; ctx.fillStyle = "rgba(255,255,255,0.94)"; ctx.font = "bold 72px Arial"; ctx.fillText("AEM-P HOVER DEMO", 72, 640); ctx.fillStyle = "rgba(255,255,255,0.88)"; ctx.font = "28px Arial"; ctx.fillText("Subtle mark + bright reveal on hover", 72, 684); ctx.strokeStyle = "rgba(255,255,255,0.45)"; ctx.lineWidth = 3; ctx.strokeRect(52, 52, c.width - 104, c.height - 104); return c }
  const copyCanvas = source => { const c = document.createElement("canvas"); c.width = source.width; c.height = source.height; c.getContext("2d").drawImage(source, 0, 0); return c };
  const imageFromFile = file => new Promise((resolve, reject) => { const url = URL.createObjectURL(file), img = new Image(); img.onload = () => resolve({ img, url }); img.onerror = reject; img.src = url });
  const canvasToDataUrl = canvas => canvas.toDataURL("image/png"), canvasHash = async canvas => sha256Hex(canvasToDataUrl(canvas));
  async function getOrCreateSigningKey() { const stored = localStorage.getItem(STORAGE_KEY); if (stored) return crypto.subtle.importKey("jwk", JSON.parse(stored), { name: "ECDSA", namedCurve: "P-256" }, !0, ["sign"]); const pair = await crypto.subtle.generateKey({ name: "ECDSA", namedCurve: "P-256" }, !0, ["sign", "verify"]); localStorage.setItem(STORAGE_KEY, JSON.stringify(await crypto.subtle.exportKey("jwk", pair.privateKey))); return pair.privateKey }
  async function getPublicJwk(privateKey) { const jwk = await crypto.subtle.exportKey("jwk", privateKey); delete jwk.d; jwk.key_ops = ["verify"]; return jwk }
  async function signManifest(manifest, privateKey) { const payload = JSON.stringify(stripManifestForSigning(manifest)); return arrayBufferToBase64(await crypto.subtle.sign({ name: "ECDSA", hash: "SHA-256" }, privateKey, new TextEncoder().encode(payload))) }
  async function verifyManifestSignature(manifest) { if (!manifest.public_key_jwk || !manifest.signature_b64) return !1; const publicKey = await crypto.subtle.importKey("jwk", manifest.public_key_jwk, { name: "ECDSA", namedCurve: "P-256" }, !0, ["verify"]); return crypto.subtle.verify({ name: "ECDSA", hash: "SHA-256" }, publicKey, base64ToUint8Array(manifest.signature_b64), new TextEncoder().encode(JSON.stringify(stripManifestForSigning(manifest)))) }
  const encodeHiddenPayloadString = payload => MAGIC + "|" + JSON.stringify(payload);
  const decodeHiddenPayloadString = s => { if (!s.startsWith(MAGIC + "|")) return null; try { return JSON.parse(s.slice(MAGIC.length + 1)) } catch { return null } };
  function embedHiddenWatermark(targetCanvas, payload) { const c = copyCanvas(targetCanvas), ctx = c.getContext("2d"), img = ctx.getImageData(0, 0, c.width, c.height), data = img.data, text = encodeHiddenPayloadString(payload), bytes = new TextEncoder().encode(text), len = bytes.length, withLen = new Uint8Array(2 + len); withLen[0] = len >> 8 & 255; withLen[1] = len & 255; withLen.set(bytes, 2); const totalBits = withLen.length * 8; if (totalBits > data.length / 4) throw new Error("Image too small for watermark payload."); let bitIndex = 0; for (let i = 0; i < withLen.length; i++)for (let b = 7; b >= 0; b--) { const bit = withLen[i] >> b & 1, px = bitIndex * 4; data[px] = data[px] & 254 | bit; bitIndex++ } ctx.putImageData(img, 0, 0); return c }
  function extractHiddenWatermark(canvas) { const ctx = canvas.getContext("2d"), img = ctx.getImageData(0, 0, canvas.width, canvas.height), data = img.data, readByte = startBit => { let v = 0; for (let i = 0; i < 8; i++) { const px = (startBit + i) * 4; v = v << 1 | data[px] & 1 } return v }; const len = (readByte(0) << 8) | readByte(8); if (!len || len > 2048) return null; const bytes = new Uint8Array(len); let bitStart = 16; for (let i = 0; i < len; i++) { bytes[i] = readByte(bitStart); bitStart += 8 } return decodeHiddenPayloadString(new TextDecoder().decode(bytes)) }
  function pixelTextPattern(char) { const maps = { "A": ["0110", "1001", "1111", "1001", "1001"], "I": ["111", "010", "010", "010", "111"], "0": ["0110", "1001", "1001", "1001", "0110"], "1": ["010", "110", "010", "010", "111"], "2": ["1110", "0001", "0110", "1000", "1111"], "3": ["1110", "0001", "0110", "0001", "1110"], "4": ["1001", "1001", "1111", "0001", "0001"], "5": ["1111", "1000", "1110", "0001", "1110"], "6": ["0111", "1000", "1110", "1001", "0110"], "7": ["1111", "0001", "0010", "0100", "0100"], "8": ["0110", "1001", "0110", "1001", "0110"], "9": ["0110", "1001", "0111", "0001", "1110"], "X": ["1001", "1001", "0110", "1001", "1001"], "·": ["0", "0", "1", "0", "0"] }; return maps[char] || ["111", "101", "101", "101", "111"] }
  function drawPixelGlyph(ctx, x, y, char, cell, color, alpha) { const rows = pixelTextPattern(char); ctx.save(); ctx.globalAlpha = alpha; ctx.fillStyle = color; for (let r = 0; r < rows.length; r++)for (let c = 0; c < rows[r].length; c++)if (rows[r][c] === "1") ctx.fillRect(x + c * cell, y + r * cell, cell - 1, cell - 1); ctx.restore(); return Math.max(...rows.map(r => r.length)) * cell }
  const markText = stateCode => "AI·" + stateCode;
  function getMarkGeometry(canvas, style) { const cell = style.pixelCell, text = markText(style.stateCode), charWidths = { "A": 4, "I": 3, "·": 1, "0": 4, "1": 3, "2": 4, "3": 4, "4": 4, "5": 4, "6": 4, "7": 4, "8": 4, "9": 4, "X": 4 }; let textW = 0; for (let i = 0; i < text.length; i++)textW += (charWidths[text[i]] || 4) * cell + cell; textW += cell * 2; const textH = 5 * cell, pad = cell * 2, boxW = textW + pad * 2, boxH = textH + pad * 2, x = canvas.width - boxW - style.offset, y = canvas.height - boxH - style.offset; return { x, y, boxW, boxH, pad, cell, text } }
  function renderSubtlePixelMark(ctx, style, hovered) { const g = getMarkGeometry(ctx.canvas, style), { x, y, boxW, boxH, pad, cell, text } = g, baseAlpha = hovered ? style.hoverAlpha : style.baseAlpha, overlayAlpha = hovered ? style.hoverGlowAlpha : .05; ctx.save(); ctx.fillStyle = hovered ? "rgba(255,255,255,0.18)" : "rgba(255,255,255,0.05)"; ctx.fillRect(x, y, boxW, boxH); const short = (style.hashShort || "00000000").slice(0, 8); for (let i = 0; i < short.length; i++) { const v = parseInt(short[i], 16); ctx.globalAlpha = hovered ? .32 : .12; ctx.fillStyle = v % 2 ? "rgba(147,197,253,1)" : "rgba(251,191,36,1)"; for (let gy = 0; gy < 3; gy++)ctx.fillRect(x + 5 + i * 6, y + 5 + gy * 4 + (v % 2), 3, 2) } ctx.globalAlpha = 1; let cx = x + pad; for (let i = 0; i < text.length; i++) { const w = drawPixelGlyph(ctx, cx, y + pad, text[i], cell, "rgba(255,255,255,1)", baseAlpha); if (hovered) drawPixelGlyph(ctx, cx, y + pad, text[i], cell, "rgba(147,197,253,1)", overlayAlpha); cx += w + cell } if (hovered) { ctx.strokeStyle = "rgba(255,255,255,0.85)"; ctx.lineWidth = 1.3; ctx.strokeRect(x - 2, y - 2, boxW + 4, boxH + 4); ctx.fillStyle = "rgba(2,6,23,0.85)"; ctx.fillRect(x - 2, y - 36, Math.max(170, boxW), 28); ctx.fillStyle = "rgba(255,255,255,0.95)"; ctx.font = "12px Arial"; ctx.fillText("AI-generated · verified state " + style.stateCode, x + 8, y - 18) } ctx.restore(); return g }
  const isInsideMark = (mx, my, geom) => geom && mx >= geom.x && mx <= geom.x + geom.boxW && my >= geom.y && my <= geom.y + geom.boxH;
  function grayscale(canvas) { const c = copyCanvas(canvas), ctx = c.getContext("2d"), img = ctx.getImageData(0, 0, c.width, c.height), d = img.data; for (let i = 0; i < d.length; i += 4) { const g = Math.round(d[i] * .299 + d[i + 1] * .587 + d[i + 2] * .114); d[i] = d[i + 1] = d[i + 2] = g } ctx.putImageData(img, 0, 0); return c }
  function invert(canvas) { const c = copyCanvas(canvas), ctx = c.getContext("2d"), img = ctx.getImageData(0, 0, c.width, c.height), d = img.data; for (let i = 0; i < d.length; i += 4) { d[i] = 255 - d[i]; d[i + 1] = 255 - d[i + 1]; d[i + 2] = 255 - d[i + 2] } ctx.putImageData(img, 0, 0); return c }
  function brighten(canvas, amount) { const c = copyCanvas(canvas), ctx = c.getContext("2d"), img = ctx.getImageData(0, 0, c.width, c.height), d = img.data; for (let i = 0; i < d.length; i += 4) { d[i] = clamp(d[i] + amount, 0, 255); d[i + 1] = clamp(d[i + 1] + amount, 0, 255); d[i + 2] = clamp(d[i + 2] + amount, 0, 255) } ctx.putImageData(img, 0, 0); return c }
  function rotate90(canvas) { const c = document.createElement("canvas"); c.width = canvas.height; c.height = canvas.width; const ctx = c.getContext("2d"); ctx.translate(c.width / 2, c.height / 2); ctx.rotate(Math.PI / 2); ctx.drawImage(canvas, -canvas.width / 2, -canvas.height / 2); return c }
  function cropCenter(canvas) { const c = document.createElement("canvas"), newW = Math.floor(canvas.width * .84), newH = Math.floor(canvas.height * .84); c.width = newW; c.height = newH; const sx = Math.floor((canvas.width - newW) / 2), sy = Math.floor((canvas.height - newH) / 2); c.getContext("2d").drawImage(canvas, sx, sy, newW, newH, 0, 0, newW, newH); return c }
  async function makeSignedManifest({ prevManifest, sourceLabel, actionType, editCountVerified, visibleState, chainStatus, canvas, breakReason, viewerStyle }) { const privateKey = await getOrCreateSigningKey(), publicJwk = await getPublicJwk(privateKey), payloadCanvasHash = await canvasHash(canvas); const manifest = { protocol_version: PROTOCOL_VERSION, asset_id: prevManifest ? prevManifest.asset_id : uuidLike(), origin_type: "ai_generated", source_label: sourceLabel || (prevManifest && prevManifest.source_label) || "demo", tool_id: "aemp.b.hover", tool_version: "0.3.0", created_at: prevManifest ? prevManifest.created_at : nowIso(), updated_at: nowIso(), action_type: actionType, edit_count_verified: editCountVerified, visible_state: visibleState, chain_status: chainStatus, prev_manifest_hash: prevManifest ? prevManifest.manifest_hash : null, break_reason: breakReason || null, payload_canvas_hash: payloadCanvasHash, viewer_style: viewerStyle, public_key_jwk: publicJwk }; manifest.manifest_hash = await sha256Hex(JSON.stringify(stripManifestForSigning(manifest))); manifest.manifest_hash_short = manifest.manifest_hash.slice(0, 16); manifest.signature_b64 = await signManifest(manifest, privateKey); return manifest }
  async function createStateBundle(payloadCanvas, manifest, hoverOn, viewerStyle) { const rendered = copyCanvas(payloadCanvas), ctx = rendered.getContext("2d"), geom = renderSubtlePixelMark(ctx, { stateCode: manifest.visible_state, hashShort: manifest.manifest_hash_short, baseAlpha: viewerStyle.baseAlpha, hoverAlpha: viewerStyle.hoverAlpha, hoverGlowAlpha: viewerStyle.hoverGlowAlpha, pixelCell: viewerStyle.pixelCell, offset: viewerStyle.offset }, hoverOn), hiddenPayload = { v: PROTOCOL_VERSION, state_code: manifest.visible_state, asset_id_short: manifest.asset_id.slice(0, 12), manifest_hash_short: manifest.manifest_hash_short, prev_manifest_hash_short: manifest.prev_manifest_hash ? manifest.prev_manifest_hash.slice(0, 12) : null, checksum: manifest.manifest_hash_short.slice(0, 4) }, embeddedCanvas = embedHiddenWatermark(rendered, hiddenPayload); return { payloadCanvas, renderedCanvas: embeddedCanvas, markGeom: geom, manifest: { ...manifest, visible_mark: "AI·" + manifest.visible_state, hidden_watermark: hiddenPayload, hover_reveal_enabled: !0, rendered_at: nowIso(), exported_canvas_hash: await canvasHash(embeddedCanvas), viewer_embed: { css: viewerCssSnippet(), html: viewerHtmlSnippet(manifest.visible_state), note: "Hover brightening is a website/app viewer behavior. The baked PNG only contains the subtle visible mark." } } } }
  async function verifyImportedPackage(pkg) { const img = new Image(); await new Promise((resolve, reject) => { img.onload = resolve; img.onerror = reject; img.src = pkg.image_data_url }); const rendered = document.createElement("canvas"); rendered.width = img.width; rendered.height = img.height; rendered.getContext("2d").drawImage(img, 0, 0); const reasons = [], manifest = pkg.manifest, signatureOk = await verifyManifestSignature(manifest); if (!signatureOk) reasons.push("signature_invalid"); const hidden = extractHiddenWatermark(rendered); if (!hidden) reasons.push("hidden_watermark_missing"); else { if (String(hidden.state_code) !== String(manifest.visible_state)) reasons.push("hidden_state_mismatch"); if (hidden.manifest_hash_short !== manifest.manifest_hash_short) reasons.push("hidden_manifest_hash_mismatch"); if (hidden.asset_id_short !== manifest.asset_id.slice(0, 12)) reasons.push("hidden_asset_id_mismatch") } const exportedHash = await canvasHash(rendered); if (exportedHash !== manifest.exported_canvas_hash) reasons.push("rendered_hash_mismatch"); const ok = reasons.length === 0 && manifest.chain_status === "valid"; return { ok, reasons, visible_state: ok ? manifest.visible_state : "X", chain_status: ok ? "valid" : "broken", manifest } }
  const panel = (title, children) => e("section", { className: "panel" }, [e("h2", { key: "t" }, title), children]);
  function App() {
    const editorCanvasRef = React.useRef(null), verifierCanvasRef = React.useRef(null); const [mode, setMode] = React.useState("editor"), [payloadCanvas, setPayloadCanvas] = React.useState(null), [renderedCanvas, setRenderedCanvas] = React.useState(null), [manifest, setManifest] = React.useState(null), [history, setHistory] = React.useState([]), [busy, setBusy] = React.useState(false), [verification, setVerification] = React.useState(null), [tamperJson, setTamperJson] = React.useState('{"visible_state":"3"}'), [hoverOn, setHoverOn] = React.useState(false), [markGeom, setMarkGeom] = React.useState(null), [viewerStyle, setViewerStyle] = React.useState({ baseAlpha: .16, hoverAlpha: .96, hoverGlowAlpha: .28, pixelCell: 5, offset: 20 });
    const addLog = React.useCallback(text => setHistory(prev => [{ ts: new Date().toLocaleTimeString(), text }, ...prev].slice(0, 50)), []);
    const syncCanvas = React.useCallback((ref, canvas) => { if (!ref.current || !canvas) return; ref.current.width = canvas.width; ref.current.height = canvas.height; ref.current.getContext("2d").drawImage(canvas, 0, 0) }, []);
    async function refreshRender(currentPayload, currentManifest, hoverState) { const bundle = await createStateBundle(currentPayload, currentManifest, hoverState, viewerStyle); setPayloadCanvas(bundle.payloadCanvas); setRenderedCanvas(bundle.renderedCanvas); setManifest(bundle.manifest); setMarkGeom(bundle.markGeom); syncCanvas(editorCanvasRef, bundle.renderedCanvas); if (mode === "verifier") syncCanvas(verifierCanvasRef, bundle.renderedCanvas); return bundle }
    async function initializeFromCanvas(sourceCanvas, sourceLabel) { setBusy(true); try { const newManifest = await makeSignedManifest({ prevManifest: null, sourceLabel, actionType: "created.ai", editCountVerified: 0, visibleState: "0", chainStatus: "valid", canvas: sourceCanvas, viewerStyle }); await refreshRender(sourceCanvas, newManifest, false); addLog("Created new signed asset with subtle visible watermark → AI·0") } finally { setBusy(false) } }
    React.useEffect(() => { initializeFromCanvas(createDemoBaseCanvas(), "demo_generator") }, []);
    React.useEffect(() => { if (!payloadCanvas || !manifest) return; refreshRender(payloadCanvas, { ...manifest, viewer_style: viewerStyle }, hoverOn) }, [viewerStyle.baseAlpha, viewerStyle.hoverAlpha, viewerStyle.hoverGlowAlpha, viewerStyle.pixelCell, viewerStyle.offset]);
    async function applyTrustedEdit(actionType, transformFn) { if (!payloadCanvas || !manifest || manifest.visible_state === "X") return; setBusy(true); try { const editedPayload = transformFn(payloadCanvas), nextCount = manifest.edit_count_verified + 1, nextState = deriveVisibleState(nextCount, false), nextManifest = await makeSignedManifest({ prevManifest: manifest, sourceLabel: manifest.source_label, actionType, editCountVerified: nextCount, visibleState: nextState, chainStatus: "valid", canvas: editedPayload, viewerStyle }); await refreshRender(editedPayload, nextManifest, false); setHoverOn(false); addLog("Trusted edit: " + actionType + " → AI·" + nextState) } finally { setBusy(false) } }
    async function metadataOnly() { if (!payloadCanvas || !manifest) return; setBusy(true); try { const nextManifest = await makeSignedManifest({ prevManifest: manifest, sourceLabel: manifest.source_label, actionType: "metadata_only", editCountVerified: manifest.edit_count_verified, visibleState: manifest.visible_state, chainStatus: manifest.chain_status, canvas: payloadCanvas, viewerStyle }); await refreshRender(payloadCanvas, nextManifest, hoverOn); addLog("Metadata-only update → state unchanged at AI·" + nextManifest.visible_state) } finally { setBusy(false) } }
    async function breakChain(reason) { if (!payloadCanvas || !manifest) return; setBusy(true); try { const brokenManifest = await makeSignedManifest({ prevManifest: manifest, sourceLabel: manifest.source_label, actionType: "chain_broken_detected", editCountVerified: manifest.edit_count_verified, visibleState: "X", chainStatus: "broken", canvas: payloadCanvas, breakReason: reason, viewerStyle }); await refreshRender(payloadCanvas, brokenManifest, false); setHoverOn(false); addLog("Forced broken chain → AI·X") } finally { setBusy(false) } }
    async function exportPackage() { if (!renderedCanvas || !manifest) return; const pkg = { package_version: 2, manifest, image_data_url: renderedCanvas.toDataURL("image/png") }, blob = new Blob([JSON.stringify(pkg, null, 2)], { type: "application/json" }); downloadBlob("aemp-package-hover.json", blob) }
    async function exportManifest() { if (!manifest) return; downloadBlob("aemp-manifest-hover.json", new Blob([JSON.stringify(manifest, null, 2)], { type: "application/json" })) }
    async function exportPng() { if (!renderedCanvas) return; renderedCanvas.toBlob(blob => blob && downloadBlob("aemp-hover-export.png", blob), "image/png") }
    async function loadPackageFile(ev) { const file = ev.target.files && ev.target.files[0]; if (!file) return; setBusy(true); try { const pkg = JSON.parse(await file.text()), img = new Image(); await new Promise((resolve, reject) => { img.onload = resolve; img.onerror = reject; img.src = pkg.image_data_url }); const canvas = document.createElement("canvas"); canvas.width = img.width; canvas.height = img.height; canvas.getContext("2d").drawImage(img, 0, 0); syncCanvas(verifierCanvasRef, canvas); setVerification(await verifyImportedPackage(pkg)); addLog("Loaded package for verification") } catch { alert("Could not load package.") } finally { setBusy(false); ev.target.value = "" } }
    async function uploadEditorImage(ev) { const file = ev.target.files && ev.target.files[0]; if (!file) return; setBusy(true); try { const loaded = await imageFromFile(file), c = document.createElement("canvas"); c.width = loaded.img.width; c.height = loaded.img.height; c.getContext("2d").drawImage(loaded.img, 0, 0); URL.revokeObjectURL(loaded.url); await initializeFromCanvas(c, "uploaded_image") } catch { alert("Could not read image.") } finally { setBusy(false); ev.target.value = "" } }
    async function tamperManifestJson() { if (!manifest || !renderedCanvas) return; setBusy(true); try { let patch = {}; try { patch = JSON.parse(tamperJson) } catch { alert("Invalid JSON patch."); setBusy(false); return } const tampered = JSON.parse(JSON.stringify(manifest)); Object.assign(tampered, patch); const pkg = { package_version: 2, manifest: tampered, image_data_url: renderedCanvas.toDataURL("image/png") }; setVerification(await verifyImportedPackage(pkg)); setMode("verifier"); syncCanvas(verifierCanvasRef, renderedCanvas); addLog("Tampered package preview sent to verifier") } finally { setBusy(false) } }
    function handleCanvasMove(ev) { if (!editorCanvasRef.current || !markGeom || !manifest) return; const rect = editorCanvasRef.current.getBoundingClientRect(), scaleX = editorCanvasRef.current.width / rect.width, scaleY = editorCanvasRef.current.height / rect.height, mx = (ev.clientX - rect.left) * scaleX, my = (ev.clientY - rect.top) * scaleY, inside = isInsideMark(mx, my, markGeom); if (inside !== hoverOn) { setHoverOn(inside); refreshRender(payloadCanvas, manifest, inside) } }
    function handleCanvasLeave() { if (!hoverOn || !payloadCanvas || !manifest) return; setHoverOn(false); refreshRender(payloadCanvas, manifest, false) }
    const stateBadge = manifest ? "AI·" + manifest.visible_state : "AI·?", verifyBadgeClass = !verification ? "badge warn" : verification.ok ? "badge good" : "badge bad";
    return e("div", { className: "container" }, [
      e("div", { className: "header", key: "head" }, [
        e("h1", { key: "h1" }, "AEM-P — Subtle Pixel Watermark with Hover Reveal - created with ChatGPT"),
        e("p", { key: "p" }, "Updated B version: the visible mark is faint and pixelated inside the image, while compatible viewers can brighten it on hover and show extra status."),
        e("div", { className: "topRow", key: "switches" }, [e("button", { key: "m1", onClick: () => setMode("editor") }, "Editor mode"), e("button", { key: "m2", onClick: () => setMode("verifier") }, "Verifier mode"), manifest ? e("span", { className: "badge", key: "b1" }, "Current state: " + stateBadge) : null])]),
      mode === "editor" ? e("div", { className: "grid", key: "editorGrid" }, [
        e("div", { key: "left" }, [
          panel("Editor controls", e("div", { className: "stack" }, [
            e("div", { className: "row", key: "states" }, [e("span", { className: "badge" }, "State: " + stateBadge), e("span", { className: "badge" }, "Chain: " + (manifest ? manifest.chain_status : "—")), e("span", { className: "badge" }, "Edits: " + (manifest ? manifest.edit_count_verified : "—"))]),
            e("div", { className: "small", key: "hint0" }, "Move the mouse over the lower-right mark area in the canvas to reveal the bright hover state."),
            e("h3", { key: "u1" }, "Image input"),
            e("div", { className: "row", key: "r1" }, [e("input", { type: "file", accept: "image/*", onChange: uploadEditorImage }), e("button", { onClick: () => initializeFromCanvas(createDemoBaseCanvas(), "demo_generator"), disabled: busy }, "New demo image")]),
            e("h3", { key: "u2" }, "Trusted edits"),
            e("div", { className: "row", key: "r2" }, [
              e("button", { onClick: () => applyTrustedEdit("filtered.grayscale", grayscale), disabled: busy || stateBadge === "AI·X" }, "Grayscale"),
              e("button", { onClick: () => applyTrustedEdit("filtered.invert", invert), disabled: busy || stateBadge === "AI·X" }, "Invert"),
              e("button", { onClick: () => applyTrustedEdit("filtered.brighten", c => brighten(c, 20)), disabled: busy || stateBadge === "AI·X" }, "Brighten"),
              e("button", { onClick: () => applyTrustedEdit("rotated.90", rotate90), disabled: busy || stateBadge === "AI·X" }, "Rotate 90°"),
              e("button", { onClick: () => applyTrustedEdit("cropped.center", cropCenter), disabled: busy || stateBadge === "AI·X" }, "Crop Center")]),
            e("h3", { key: "u2b" }, "Watermark appearance"),
            e("div", { className: "sliderLabel" }, [e("span", null, "Subtle opacity"), e("span", null, viewerStyle.baseAlpha.toFixed(2))]),
            e("input", { type: "range", min: "0.05", max: "0.35", step: "0.01", value: viewerStyle.baseAlpha, onChange: ev => setViewerStyle({ ...viewerStyle, baseAlpha: Number(ev.target.value) }) }),
            e("div", { className: "sliderLabel" }, [e("span", null, "Hover opacity"), e("span", null, viewerStyle.hoverAlpha.toFixed(2))]),
            e("input", { type: "range", min: "0.70", max: "1.00", step: "0.01", value: viewerStyle.hoverAlpha, onChange: ev => setViewerStyle({ ...viewerStyle, hoverAlpha: Number(ev.target.value) }) }),
            e("div", { className: "sliderLabel" }, [e("span", null, "Pixel size"), e("span", null, String(viewerStyle.pixelCell))]),
            e("input", { type: "range", min: "3", max: "8", step: "1", value: viewerStyle.pixelCell, onChange: ev => setViewerStyle({ ...viewerStyle, pixelCell: Number(ev.target.value) }) }),
            e("div", { className: "sliderLabel" }, [e("span", null, "Corner offset"), e("span", null, String(viewerStyle.offset))]),
            e("input", { type: "range", min: "12", max: "40", step: "1", value: viewerStyle.offset, onChange: ev => setViewerStyle({ ...viewerStyle, offset: Number(ev.target.value) }) }),
            e("h3", { key: "u3" }, "Special actions"),
            e("div", { className: "row", key: "r3" }, [e("button", { onClick: metadataOnly, disabled: busy }, "Metadata only"), e("button", { onClick: () => breakChain("edited_outside_trusted_toolchain"), disabled: busy }, "Force broken chain → X")]),
            e("h3", { key: "u4" }, "Export"),
            e("div", { className: "row", key: "r4" }, [e("button", { onClick: exportPng, disabled: busy }, "Download PNG"), e("button", { onClick: exportManifest, disabled: busy || !manifest }, "Download manifest"), e("button", { onClick: exportPackage, disabled: busy || !manifest }, "Download AEM-P package")]),
            e("h3", { key: "u5" }, "Tamper test"),
            e("div", { className: "small", key: "tt" }, "Patch the manifest without re-signing it, then send it to verifier mode."),
            e("textarea", { value: tamperJson, onChange: ev => setTamperJson(ev.target.value) }),
            e("div", { className: "row" }, [e("button", { onClick: tamperManifestJson, disabled: busy || !manifest }, "Send tampered package to verifier")])
          ])),
          panel("Event log", e("div", { className: "log" }, history.length ? history.map((item, idx) => e("div", { className: "logItem", key: idx }, [e("div", { className: "small", key: "t" }, item.ts), e("div", { key: "x" }, item.text)])) : e("div", { className: "small" }, "No events yet.")))
        ]),
        e("div", { key: "center" }, panel("Rendered image", e("div", { className: "canvasWrap" }, [e("canvas", { ref: editorCanvasRef, onMouseMove: handleCanvasMove, onMouseLeave: handleCanvasLeave })]))),
        e("div", { key: "right" }, [
          panel("Signed manifest", e("pre", null, manifest ? JSON.stringify(manifest, null, 2) : "Loading…")),
          panel("What changed", e("div", null, [
            e("div", { className: "kv", key: "k1" }, [e("div", { className: "k" }, "Visible mark"), e("div", { className: "v" }, "Now subtle, pixelated, and baked into the PNG")]),
            e("div", { className: "kv", key: "k2" }, [e("div", { className: "k" }, "Hover reveal"), e("div", { className: "v" }, "Compatible viewer can brighten and explain the mark")]),
            e("div", { className: "kv", key: "k3" }, [e("div", { className: "k" }, "Export JSON"), e("div", { className: "v" }, "Includes CSS and HTML snippets for website display")]),
            e("div", { className: "small", key: "note" }, "The hover effect is part of the website/app viewer. The exported PNG itself only stores the subtle visible mark plus the hidden watermark.")
          ]))])])
        : e("div", { className: "grid", key: "verifierGrid" }, [
          e("div", { key: "left" }, panel("Verifier controls", e("div", { className: "stack" }, [
            e("div", { className: verifyBadgeClass, key: "verifyState" }, verification ? (verification.ok ? "Verified: AI·" + verification.visible_state : "Verification failed → AI·X") : "Load an AEM-P package to verify"),
            verification ? e("div", { className: "small", key: "reasons" }, verification.ok ? "All checks passed." : "Reasons: " + verification.reasons.join(", ")) : null,
            e("h3", { key: "u1" }, "Load package"),
            e("input", { type: "file", accept: ".json,application/json", onChange: loadPackageFile }),
            e("div", { className: "small", key: "s1" }, "Expected file: the AEM-P package JSON exported from editor mode, containing a PNG data URL, the signed manifest, and viewer embed hints.")
          ]))),
          e("div", { key: "center" }, panel("Verified image preview", e("div", { className: "canvasWrap" }, [e("canvas", { ref: verifierCanvasRef })]))),
          e("div", { key: "right" }, [
            panel("Verification output", e("pre", null, verification ? JSON.stringify(verification, null, 2) : "No package loaded.")),
            panel("Interpretation", e("div", null, [
              e("div", { className: "kv", key: "i1" }, [e("div", { className: "k" }, "AI·0"), e("div", { className: "v" }, "AI-made, 0 verified edits")]),
              e("div", { className: "kv", key: "i2" }, [e("div", { className: "k" }, "AI·1–8"), e("div", { className: "v" }, "Exact verified edit count")]),
              e("div", { className: "kv", key: "i3" }, [e("div", { className: "k" }, "AI·9"), e("div", { className: "v" }, "Nine or more verified edits")]),
              e("div", { className: "kv", key: "i4" }, [e("div", { className: "k" }, "AI·X"), e("div", { className: "v" }, "Broken provenance or tampered package")])
            ]))])])
    ])
  }
  ReactDOM.createRoot(document.getElementById("root")).render(e(App))
})();